name: Deploy To EC2

on:
  push:
    branches:
      - main


jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: EC2 서버에 접속하기
        uses: appleboy/ssh-action@v1.0.3
        env:
          DOCKER_ID: ${{ secrets.DOCKER_ID }}
          DOCKER_PW: ${{ secrets.DOCKER_PW }}
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script_step: true
          script: |
            cd /home/ubuntu/spring-boot
            git pull origin main
            sudo ./gradlew clean build
            sudo fuser -k -n tcp 8080 || true
            echo "$DOCKER_PW" | docker login -u "$DOCKER_ID" --password-stdin
            docker pull "$DOCKER_ID"/spring-boot-demo:lastest
            sudo docker build -t "$DOCKER_ID"/spring-boot-demo:latest .
            nohup sudo docker run -d -p 8080:8080 "$DOCKER_ID"/spring-boot-demo > ./output.log 2 >&1 &