name: Deploy To EC2

on:
  push:
    branches:
      - main


jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: docker hub 로그인
        uses: docker/login-action@v2
        with:
            username: ${{ secrets.DOCKER_ID }}
            password: ${{ secrets.DOCKER_PW }}

      - name: SSH(원격접속)로 EC2에 접속하기
        uses: appleboy/ssh-action@v1.0.3
        env:
          APPLICATION_PROPERTIES: ${{ secrets.APPLICATION_PROPERTIES }}
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          envs: APPLICATION_PROPERTIES
          scripts_step: true
          script: |
            # 환경 설정
            cd /home/ubuntu/spring-boot
            rm -rf src/main/resources/application.yml
            git pull origin main
            echo "$APPLICATION_PROPERTIES" > src/main/resources/application.yml
            sudo ./gradlew clean build -x test
            
            # port kill
            sudo fuser -k -n tcp 8080 || true
            sudo fuser -k -n tcp 3306 || true

            # 실행 중인 컨테이너 삭제
            sudo docker rm -f springboot
            sudo docker rm -f db-mysql
            
            # container pull
            sudo docker pull ${{ secrets.DOCKER_ID }}/spring-boot-demo:mysql1.0
            sudo docker pull ${{ secrets.DOCKER_ID }}/spring-boot-demo:springboot1.0
            
            # container 실행
            sudo docker run -d --name db-mysql --network springboot-mysql-net -p 3306:3306 -e MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }} ${{ secrets.DOCKER_ID }}/spring-boot-demo:mysql1.0
            sudo docker run -d --name springboot --network springboot-mysql-net -p 8080:8080 ${{ secrets.DOCKER_ID }}/spring-boot-demo:springboot1.0
            sudo docker ps -a
            nohup java -jar build/libs/*SNAPSHOT.jar > ./output.log 2 >& 1 &