name: Deploy To EC2

on:
  push:
    branches:
      - main

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: docker hub 로그인
        uses: docker/login-action@v2
        with:
            username: ${{ secrets.DOCKER_ID }}
            password: ${{ secrets.DOCKER_PW }}

      - name: SSH(원격접속)로 EC2에 접속하기
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          scripts_step: true
          script: |
            cd /home/ubuntu/spring-boot
            git pull origin main
            sudo ./gradlew clean build
            sudo fuser -k -n tcp 8080 || true
            sudo docker stop $(sudo docker ps -aq)
            sudo docker pull ${{ secrets.DOCKER_ID }}/spring-boot-demo:latest
            sudo docker run -d -p 8080:8080 ${{ secrets.DOCKER_ID }}/spring-boot-demo:latest
